version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

#  app:
#    image: spring-rabbit:0.0.1-SNAPSHOT
#    restart: always
#    ports:
#      - "8007:8007"
#    depends_on:
#      - rabbitmq
